### PR TITLE
Adx 380 Access Restrictions Bug

### PR DESCRIPTION
**Pull request by jonathansberry**
This PR is still unfinished.  I'm not convinced I have got to the bottom of the issue.  It also needs tests.

### CODE REVIEW

**Review by jonathansberry — COMMENTED** [review]
We could unit test the convert_from_extras_nested once we are convinced of the behaviour it should follow.  We should perhaps also validate that the nested function is actually used? Though this would be a notable departure from the core ckanext-scheming.

**Comment by jonathansberry** [comment]
Build failed, test runs locally.  Testing this is a bit tricky because the test depends on both restricted and scheming extensions. Scheming/Validation/Restrict/UNAIDS are all coupled in some slightly messy way.

**Comment by jonathansberry** [comment]
This is a scheming specific bug: any additional resource fields to CKAN's default resource schema are duplicated between the first and the last resource.  It has nothing to do with the restricted extension.

**Comment by jonathansberry** [comment]
Regression test works well I think.  I have noted that the way converting from extras happens is done differently upstream.  I wonder if this is the sort of thing that has already been fixed there. It really seems to me like a blantent bug on scheming's part. https://github.com/ckan/ckanext-scheming/blob/c968dd09f16bd9e1d179c137d303cda52cc67dc3/ckanext/scheming/plugins.py#L257

**Comment by jonathansberry** [comment]
So this is a much more robust fix now I think.  I have essentially copied upstream scheming validate function and added Gunnar's change on top of it. But I think we should have a few more tests to check that that resource validation works well.

**Review by tomeksabala — APPROVED** [review]
This looks good. I needed to change the test class name and filename so I get the tests working with nosetests locally.
Together with this change I've updated some minor changes. If you don't mind go ahead with the merge.

**Pull request merged**
